name: Build .NET Console App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore
        
      - name: build
        run: dotnet build -c Release

      - name: Publish Windows
        run: dotnet publish Isitar.PdfManipulator.csproj -c Release -r 'win-x64' --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -o ./publish-windows

      - name: Publish Linux
        run: dotnet publish Isitar.PdfManipulator.csproj -c Release -r 'linux-x64' --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -o ./publish-linux
        
      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: console-app-windows
          path: ./publish-windows/*.exe

      - name: Upload Linux Executable
        uses: actions/upload-artifact@v4
        with:
          name: console-app-linux
          path: ./publish-linux/*
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: console-app-windows
          path: ./publish-windows

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: console-app-linux
          path: ./publish-linux

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}  # Increment versioning as needed
          name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            publish-linux/*
            publish-windows/*